# Generated by Django 5.1.4 on 2025-01-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_schoolclass_remove_product_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
