# Generated by Django 5.1.4 on 2025-01-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
