# Generated by Django 5.1.4 on 2025-01-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_schoolnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolnumber',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
