# Generated by Django 5.1.4 on 2025-01-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_schoolnumber_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolnumber',
            old_name='phone_number',
            new_name='school_number',
        ),
        migrations.AlterField(
            model_name='schoolnumber',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
