# Generated by Django 5.1.4 on 2025-01-18 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_remove_schoolclass_class_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='time',
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=11)),
                ('time', models.TimeField()),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='index.schoolclass')),
            ],
        ),
    ]
