# Generated by Django 5.1.4 on 2025-01-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_alter_classschedule_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='time',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='hour',
            field=models.IntegerField(choices=[(0, '00'), (1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23')], default=0),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='minute',
            field=models.IntegerField(choices=[(0, '00'), (5, '05'), (10, '10'), (15, '15'), (20, '20'), (25, '25'), (30, '30'), (35, '35'), (40, '40'), (45, '45'), (50, '50'), (55, '55')], default=0),
        ),
    ]
