# Generated by Django 5.1.4 on 2025-02-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_remove_classschedule_time_classschedule_hour_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Заявка клиента', 'verbose_name_plural': 'Заявки клиентов'},
        ),
        migrations.AlterModelOptions(
            name='schoolnumber',
            options={'verbose_name': 'Телефон школы', 'verbose_name_plural': 'Телефон школы'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_number',
            field=models.CharField(help_text='Format: +998xxxxxxxxx', max_length=19, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='schoolnumber',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название школы'),
        ),
        migrations.AlterField(
            model_name='schoolnumber',
            name='school_number',
            field=models.CharField(max_length=20, verbose_name='Номер школы'),
        ),
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название занятия')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('schedule_day_of_week', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=20, verbose_name='День недели')),
                ('schedule_hour', models.PositiveIntegerField(choices=[(7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], verbose_name='Час')),
                ('schedule_minute', models.PositiveIntegerField(choices=[(0, '00'), (15, '15'), (30, '30'), (45, '45')], verbose_name='Минута')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
                'ordering': ['schedule_day_of_week', 'schedule_hour', 'schedule_minute'],
                'unique_together': {('name', 'schedule_day_of_week', 'schedule_hour', 'schedule_minute')},
            },
        ),
        migrations.DeleteModel(
            name='ClassSchedule',
        ),
        migrations.DeleteModel(
            name='SchoolClass',
        ),
    ]
