# Generated by Django 5.1.4 on 2025-02-05 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_alter_contact_options_alter_schoolnumber_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classname',
            options={'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AlterUniqueTogether(
            name='classname',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='classname',
            name='schedule_day_of_week',
        ),
        migrations.RemoveField(
            model_name='classname',
            name='schedule_hour',
        ),
        migrations.RemoveField(
            model_name='classname',
            name='schedule_minute',
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=20, verbose_name='День недели')),
                ('hour', models.PositiveIntegerField(choices=[(7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], verbose_name='Час')),
                ('minute', models.PositiveIntegerField(choices=[(0, '00'), (15, '15'), (30, '30'), (45, '45')], verbose_name='Минута')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='index.classname', verbose_name='Занятие')),
            ],
            options={
                'verbose_name': 'Расписание занятий',
                'verbose_name_plural': 'Расписание занятий',
                'ordering': ['day_of_week', 'hour', 'minute'],
                'unique_together': {('school_class', 'day_of_week', 'hour', 'minute')},
            },
        ),
    ]
