# Generated by Django 5.1.4 on 2025-02-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_alter_classname_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_number',
            field=models.CharField(help_text='Format: +998(xx)xxx-xx-xx', max_length=19, verbose_name='Номер телефона'),
        ),
    ]
